name: Test Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [
          {"name": "LTS", "version": "lts/-2"},
          {"name": "latest", "version": "latest"}
        ]
    name: Node ${{ matrix.node.name }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node.name }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node.version }}
      - run: npm install
      - run: make public
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node.name }}
          path: dist
          retention-days: 30
      - run: START_MODE=dev npm run test:e2e
      - run: START_MODE=prod npm run test:e2e
